[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://identity.netlify.com https://unpkg.com 'unsafe-eval';
      script-src-elem 'self' https://identity.netlify.com https://unpkg.com 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self' https://api.netlify.com https://identity.netlify.com https://github.com https://raw.githubusercontent.com;
      frame-src 'self' https://identity.netlify.com;
      worker-src 'self' blob:;
    """