[build]
  command = "npm run build"
  publish = "dist"

# CSP только для админки: разрешаем unpkg, identity и unsafe-eval
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://unpkg.com https://identity.netlify.com 'unsafe-eval';
      style-src  'self' 'unsafe-inline';
      img-src    'self' data: https:;
      connect-src 'self' https://api.netlify.com https://identity.netlify.com https://github.com https://raw.githubusercontent.com;
      frame-src  'self' https://identity.netlify.com;
      worker-src 'self' blob:;
    """

# (опционально) общий CSP для остального сайта — без unsafe-eval и без inline-скриптов
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self';
      style-src  'self';
      img-src    'self' data:;
      connect-src 'self';
    """