[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/go/*"
  to = "/.netlify/functions/go/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    # ЕДИНСТВЕННЫЙ CSP заголовок. Разрешаем Supabase (REST+WS), Plausible и Netlify API.
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data: blob: https:; font-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' https://plausible.io; script-src-elem 'self' https://plausible.io; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://plausible.io https://api.netlify.com; frame-src 'none'; worker-src 'self' blob:;"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"