[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/go/*"
  to = "/.netlify/functions/go/:splat"
  status = 200
  force = true
  

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com;
      script-src-elem 'self' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: https://www.google-analytics.com;
      connect-src 'self' https://www.google-analytics.com https://*.supabase.co wss://*.supabase.co;
      frame-src 'none';
      worker-src 'self' blob:;
      base-uri 'self';
      frame-ancestors 'none';
      form-action 'self';
      font-src 'self' data:;
    """