[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API-функция (если нужна)
[[redirects]]
  from = "/go/*"
  to = "/.netlify/functions/go/:splat"
  status = 200
  force = true

# ---- Security headers + CSP для всех путей
[[headers]]
  for = "/*"
  [headers.values]
    # CSP: без wildcard в img-src; без unsafe-inline в style-src
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com;
      script-src-elem 'self' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self';
      img-src 'self' data: https://www.google-analytics.com;
      connect-src 'self' https://www.google-analytics.com https://*.supabase.co wss://*.supabase.co;
      font-src 'self' data:;
      object-src 'none';
      base-uri 'self';
      frame-ancestors 'none';
      form-action 'self';
      worker-src 'self' blob:;
    """

    # Spectre mitigation + прочее
    Cross-Origin-Resource-Policy = "same-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"

    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "DENY"

    # Отключаем доступ к чувствительным фичам
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# HTML — не кэшируем
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Долгий кэш для сгенерированных ассетов Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"