backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "offers"
    label: "Офферы"
    folder: "public/content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Название", name: "name", widget: "string"}
      - {label: "Рейтинг", name: "rating", widget: "number"}
      - {label: "Лицензия", name: "license", widget: "string"}
      - {label: "Выплаты", name: "payout", widget: "string"}
      - {label: "Методы", name: "methods", widget: "string"}
      - {label: "Ссылка", name: "link", widget: "string"}
      - {label: "Включено", name: "enabled", widget: "boolean"}
      - {label: "Позиция", name: "position", widget: "number"}