backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: home
    label: Главная
    format: json
    files:
      - name: home_texts         # ← ЭТО обязателен
        label: Тексты
        file: content/home.json  # URL-путь без "public/"
        fields:
          - { name: badge, label: Бейдж, widget: string }
          - { name: title, label: Заголовок, widget: string }
          - { name: subtitle, label: Подзаголовок, widget: text }

  - name: offers
    label: Офферы
    format: json
    files:
      - name: offers_list        # ← ЭТО обязателен
        label: Список офферов
        file: content/offers.json
        fields:
          - name: items
            label: Элементы
            widget: list
            fields:
              - { name: name,     label: Название, widget: string }
              - { name: rating, label: Рейтинг, widget: number, value_type: float, min: 0, max: 5, step: 0.1 }
              - { name: license,  label: Лицензия, widget: string }
              - { name: payout,   label: Выплаты,  widget: string }
              - { name: methods,  label: Методы,   widget: string }
              - { name: link,     label: Ссылка,   widget: string }
              - { name: enabled,  label: Активен,  widget: boolean, default: true }
              - { name: position, label: Позиция,  widget: number,  default: 1 }