backend:
  name: git-gateway
  branch: main # или master, в зависимости от твоей ветки

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Главная страница"
    files:
      - file: "public/content/home.json"
        label: "Тексты главной"
        fields:
          - { name: "badge", label: "Бейдж", widget: "string" }
          - { name: "title", label: "Заголовок", widget: "string" }
          - { name: "subtitle", label: "Подзаголовок", widget: "string" }

  - name: "offers"
    label: "Казино"
    files:
      - file: "public/content/offers.json"
        label: "Список казино"
        fields:
          - label: "Казино"
            name: "items"
            widget: "list"
            fields:
              - { name: "name", label: "Название", widget: "string" }
              - { name: "rating", label: "Рейтинг", widget: "number", step: 0.1 }
              - { name: "license", label: "Лицензия", widget: "string" }
              - { name: "payout", label: "Время выплат", widget: "string" }
              - { name: "methods", label: "Методы пополнения", widget: "string" }
              - { name: "link", label: "Партнёрская ссылка", widget: "string" }
              - { name: "enabled", label: "Вкл/Выкл", widget: "boolean", default: true }
              - { name: "position", label: "Позиция", widget: "number" }